const data = {
    products: [
        {
        name : 'Anillo de Compromiso, Esmeralda en Plata 9,25',
        slug: 'Anillo de Compromiso, Esmeralda en Plata 9,25',
        category: 'Rings',
        image: '/images/img1.png',
        price: 120,
        countInStock: 10,
        brand: 'Esmeralda',
        rating: 4.5,
        numReviews: 10,
        description: 'High quality shirt',
    },
    {
        name : 'Argollas de matrimonio en Oro de 18 Kilates',
        slug: 'argollas de matrimonio en Oro de 18 Kilates',
        category: 'Rings',
        image: '/images/img2.png',
        price: 350,
        countInStock: 5,
        brand: 'Esmeralda',
        rating: 4.0,
        numReviews: 10,
        description: 'High quality shirt',
    },
    {
        name : 'Anillo Esmeralda Simulada',
        slug: 'anillo-esmeralda-simulada',
        category: 'Rings',
        image: '/images/img3.png',
        price: 25,
        countInStock: 15,
        brand: 'Esmeralda',
        rating: 4.5,
        numReviews: 14,
        description: 'High quality shirt; Plata 9,25',
    },
    {
        name : 'Collar Esmeralda Rusa y Circones',
        slug: 'collar-esmeralda-rusa',
        category: 'Shirts',
        image: '/images/img4.png',
        price: 65,
        countInStock: 5,
        brand: 'Esmeralda',
        rating: 4.0,
        numReviews: 10,
        description: 'High quality shirt',
    },
],
};

export default data;